rootProject.name = 'Company-Microservices'

// Libraries
include 'libraries:common-core'
include 'libraries:common-dto'
include 'libraries:common-security'

// Infrastructure
include 'infrastructure:Eureka-Server'
include 'infrastructure:Config-Server'
include 'infrastructure:Api-Gateway'

// Services
include 'service:User-Service'
include 'service:email-service'
// Customizing project paths (Optional, but cleaner)
project(':libraries:common-core').projectDir = file('libraries/common-core')
project(':libraries:common-dto').projectDir = file('libraries/common-dto')
project(':libraries:common-security').projectDir = file('libraries/common-security')
project(':infrastructure:Eureka-Server').projectDir = file('infrastructure/Eureka-Server')
project(':infrastructure:Config-Server').projectDir = file('infrastructure/Config-Server')
project(':infrastructure:Api-Gateway').projectDir = file('infrastructure/Api-Gateway')
project(':service:User-Service').projectDir = file('service/User-Service')
project(':service:email-service').projectDir = file('service/email-service')
